version: "3.1"

services:
  montage-auth-service:
    restart: always
    image: montagestudio/montage-auth-service:develop-SNAPSHOT
    volumes:
      - ./:/home/montage-auth-service/public/:ro
    environment:
      # Monatge Auth App
      APP_SECRET: 'd1087d4bb3533a72d690efd990dfc65e9de097d982f60cbb33f52388befc1c86'
      APP_SSL: 'false'
      APP_PORT: '80'
      APP_HOST: 'localhost'
      APP_URL: 'https://auth.disasteraware.com'
      # JWT config
      JWKS_URI: 'https://testenterprise.disasteraware.com/jwt/jwks.json'
      JWKS_ISSUER: 'https://testenterprise.disasteraware.com/jwt/jwks.json'
      # Zendesk config
      ZENDESK_TOKEN_SECRET: '9ta9csrdHPnsKMFCXTxuvZqqIJ1BHEduLi9YEXbqaGUMZqTj'
    ports:
      - 80:80
    networks:
      - back

networks:
  back: