swagger: "2.0"
info:
  description: |
    This is an external Montage Auth Server REST API documentation. 
  version: "0.0.1"
  title: "Montage Auth REST API"
  contact:
    email: "support@montagestudio.com"
host: ""
basePath: ""
schemes:
- "https"
- "http"
paths:
  /auth/twitter:  
    get:
      tags:
        - "twitter"
      responses:
        302:
          description: "Successful operation"
    post:
      tags:
        - "twitter"
      responses:
        302:
          description: "Successful operation"
  /auth/twitter/callback:
    get:
      tags:
        - "twitter"
      responses:
        200:
          description: "Successful operation"

  /api/twitter/:twitterObject/:twitterAction:
    get:
      tags:
        - "twitter"
      responses:
        200:
          description: "Successful operation"
  /auth/github:
    get:
      tags:
        - "github"
      responses:
        302:
          description: "Successful operation"
    post:
      tags:
        - "github"
      responses:
        302:
          description: "Successful operation"
  /auth/github/callback:
    get:
      tags:
        - "github"
      responses:
        200:
          description: "Successful operation"
  /auth/jwtks:
    get:
      tags:
        - "jwtks"
      responses:
        200:
          description: "Successful operation"
  /auth/zendesk:
    get:
      tags:
        - "zendesk"
      responses:
        302:
          description: "Successful operation"
    post:
      tags:
        - "zendesk"
      responses:
        302:
          description: "Successful operation"
  /auth/zendesk/callback:
    get:
      tags:
        - "zendesk"
      responses:
        200:
          description: "Successful operation"
  /api/zendesk/token:
    get:
      tags:
        - "zendesk"
      parameters:
      - name: "email"
        in: "query"
        description: "User email to authenticate"
        required: true
        type: "string"
        format: "string"
      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ZendeskToken"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        401:
          $ref: '#/components/responses/UnauthorizedError'
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Requests should pass an Authorization header with a Bearer token.
security:
  - requestedWithXHR: []
  - bearerAuth: []
  - apiKey: []
  - xsrfToken: []
definitions:
  ZendeskToken:
    type: "object"
    properties:
      token:
        type: "string"
        format: "string"
      url:
        type: "string"
        format: "string"
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid